; Fake Monitor Players schedule rules
; Priority: ONLINE rules > TIME rules
;
; TIME format:
; TIME HH:MM-HH:MM fake_min fake_max
TIME 00:00-08:59 14 18
TIME 09:00-17:59 8 12
TIME 18:00-23:59 10 16

; ONLINE format:
; ONLINE real_min real_max fake_min fake_max
ONLINE 0 5 12 18
ONLINE 6 12 8 12
ONLINE 13 20 4 8
ONLINE 21 32 0 2
